index.js, package.json, src/components/input/InputSelect.tsx, src/components/input/InputText.tsx
=> InputSelect and InputText components added

src/components/app/JepAppContext.tsx, src/components/app/JepWorkstate.ts, src/components/app/index.ts, src/index.ts
=> App common components

packages/datepicker/package.json, packages/datepicker/src/DatePicker.tsx, packages/datepicker/stories/datepicker.stories.tsx, packages/input/package.json, packages/input/src/MaskedInput.tsx, packages/input/stories/maskedinput.stories.tsx, yarn.lock
заменена библиотека на react-text-mask
=> fix: masked input and datepicker fixes

packages/combobox/src/ComboBox.tsx, packages/input/src/DecimalInput.tsx, packages/input/src/NumberInput.tsx, packages/input/src/SelectInput.tsx, packages/input/src/TextInput.tsx, packages/input/src/styles.tsx
=> fix: input style props

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx
=> feat: combobox arrow navigation

.github/workflows/test.yml
=> ci: add linter

packages/datepicker/test/datepicker.test.tsx, packages/duallist/test/__snapshots__/duallist.test.tsx.snap, packages/duallist/test/duallist.test.tsx, packages/form/tests/form.test.tsx, packages/grid/tests/grid.test.tsx
добавлена простая проверка взаимодействий с полями
TBD
=> test: added simple check of interactions with fields

packages/grid/src/grid/Grid.tsx, packages/grid/stories/grid.stories.tsx, packages/grid/tests/__snapshots__/grid.test.tsx.snap
=> fix: grid row count

examples/formik-forms/src/App.tsx, packages/combobox/src/ComboBox.tsx, packages/combobox/src/ComboBoxButton.tsx, packages/combobox/stories/combobox.stories.tsx, packages/combobox/tests/__snapshots__/combobox.test.tsx.snap, packages/combobox/tests/combobox.test.tsx
Возникал exception при передаче в комбобокс следующего набора children:
```
<ComboBox>
<ComboBoxItem/>
{[...].map(option => <ComboBoxItem/>)}
</ComboBox>
```
Комбинация массива ReactNode и одного ReactNode вызывала несостыковку типов при поиске выделенного значения.
=> fix: undefined option error

packages/grid/src/grid/Grid.tsx
=> fix: grid default page

packages/grid/src/grid/Grid.tsx, packages/grid/stories/grid.stories.tsx
=> feat: onRefresh callback added in props

packages/datepicker/test/__snapshots__/datepicker.test.tsx.snap, packages/duallist/test/__snapshots__/duallist.test.tsx.snap, packages/grid/tests/__snapshots__/grid.test.tsx.snap, packages/input/src/styles.tsx, packages/input/tests/__snapshots__/decimalInput.test.tsx.snap, packages/input/tests/__snapshots__/maskedTextInput.test.tsx.snap, packages/input/tests/__snapshots__/moneyInput.test.tsx.snap, packages/input/tests/__snapshots__/numberInput.test.tsx.snap, packages/input/tests/__snapshots__/selectInput.test.tsx.snap, packages/input/tests/__snapshots__/textInput.test.tsx.snap, packages/table/src/common/TableHeader.tsx, packages/table/src/common/TableRow.tsx, packages/table/tests/__snapshots__/table.test.tsx.snap
=> fix: table cell flex display property wasn't inherited in IE

packages/grid/src/styles/index.ts, packages/grid/tests/__snapshots__/grid.test.tsx.snap
=> fix: grid selection

packages/grid/package.json, packages/grid/src/grid/Grid.tsx, packages/grid/src/styles/index.ts, packages/grid/tests/__snapshots__/grid.test.tsx.snap, packages/table/src/common/TableBody.tsx, packages/table/tests/__snapshots__/table.test.tsx.snap
=> fix: absolute elements positioning

packages/combobox/src/ComboBox.tsx, packages/combobox/src/ComboBoxItem.tsx, packages/combobox/src/index.ts, packages/combobox/src/react-app-env.d.ts, packages/combobox/src/styles.tsx, packages/combobox/stories/combobox.stories.tsx
=> feat: default input value

packages/grid/package.json, packages/grid/src/ColumnConfigPanel.tsx, packages/grid/src/Grid.tsx, packages/grid/src/index.ts, packages/grid/src/styles.tsx, packages/grid/src/useColumnConfiguration.ts, packages/pagingbar/package.json, packages/pagingbar/src/index.tsx, packages/pagingbar/tests/pagingtoolbar.test.tsx, packages/table/package.json, packages/table/src/common/TablePagingBar.tsx, packages/table/src/common/TableRow.tsx, packages/table/stories/table.stories.tsx, yarn.lock
refactor: column configuration hook
TBD
=> refactor: grid paging bar

packages/grid/src/Grid.tsx, packages/grid/stories/grid.stories.tsx
=> feat: fetchData prop added

packages/combobox/src/ComboBox.tsx, packages/combobox/src/ComboBoxButton.tsx, packages/combobox/src/styles.tsx, packages/combobox/stories/combobox.stories.tsx
=> fix: combobox fixes for cases when its parent is scrollable

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx
=> fix: combobox option values as objects

examples/formik-forms/src/App.tsx, packages/datepicker/package.json, packages/datepicker/src/DatePicker.tsx, packages/datepicker/stories/datepicker.stories.tsx, packages/datepicker/test/datepicker.test.tsx, packages/utils/src/dateUtils.ts, packages/utils/src/index.ts, yarn.lock
=> feat(datepicker): add ISO string support

packages/checkbox-group/package.json, packages/checkbox-group/src/CheckBoxGroup.tsx, packages/checkbox-group/stories/checkbox-group.stories.tsx, packages/checkbox-group/tests/checkboxgroup.test.tsx
=> feat: selectAll props added

packages/grid/src/styles.tsx
=> fix: cell will take 100% on mobile

packages/combobox/src/styles.tsx
=> fix: combobox icons centered

packages/combobox/src/ComboBox.tsx
=> fix: default filtering is made with upper case

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx
=> fix: when filter text is invalid it will be cleared on blur

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx, yarn.lock
=> fix: combobox didn't react on value prop changes

packages/combobox/src/ComboBox.tsx, packages/duallist/package.json, packages/duallist/src/DualList.tsx, packages/duallist/src/styles.tsx, packages/duallist/stories/duallist.stories.tsx, packages/duallist/test/duallist.test.tsx, packages/hooks/src/useFilter/useFilter.ts
=> refactor: dual list refactored to be controlled component

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx
=> fix: when options were loaded async, initial value wasn't displayed

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx
=> fix: combobox ref

packages/duallist/src/DualList.tsx, packages/duallist/stories/duallist.stories.tsx
=> fix: dual list filter with upper case

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx, packages/popup/package.json, packages/popup/src/Popup.tsx, packages/popup/stories/popup.stories.tsx
=> feat: popup flip onscreen overflow

packages/combobox/src/ComboBox.tsx, packages/combobox/stories/combobox.stories.tsx, packages/popup/src/Popup.tsx
fix: combobox async filter
TBD
=> fix: popup changing coords on on open

packages/combobox/src/ComboBox.tsx
=> fix: onBlur
